<?php
namespace DepartmentPostDepartmentPostView\Logic;

use DepartmentPostDepartmentPostView\Model\DepartmentPostDepartmentPostViewModel;

class DepartmentPostDepartmentPostView extends DepartmentPostDepartmentPostViewModel
{

}